config/routes.rb
Rails.application.routes.draw do
  resources :plans

  namespace :auth do
    resources :sessions
  end

  resources :membership_types
  resources :memberships
  resources :work_sessions
  resources :companies
  resources :purchases
  resources :products
  resources :users do
    member do
      get  :actions
      get :confirmation
      patch :update_confirmation
      get :manage_memberships
      get :manage
      get :set_pin
      patch :update_pin
      get :thank_you

    end
    resources :purchases
    resources :work_sessions do
      member do
        post :checkout
      end
      collection do
        post :checkin
      end
    end
  end
  resources :spaces do
    resources :space_products
  end

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  post '/products/products', to: 'products#tablet'
  post '/tablet/products', to: 'products#tablet'
  post 'tablet/chargebee_products', to: 'products#tablet_chargebee'
  post '/push_cobot_purchase/purchases', to: 'purchases#push_cobot_purchase'
  post '/push_chargebee_purchases', to: 'purchases#push_chargebee_purchase'
  get '/tablet', to: 'users#tablet'
  get '/sign_up', to: 'users#sign_up'

  root 'users#index'

end 

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :space
  belongs_to :user
  has_one :membership_type
end

app/models/membership_type.rb
class MembershipType < ActiveRecord::Base
  belongs_to :membership
  belongs_to :product
  belongs_to :plan
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  skip_before_filter :logged_in_using_omniauth?
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership_types = MembershipType.all
    @user = User.find(params[:user_id])
    @membership= Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end


  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to set_pin_user_path(membership_params[:user_id]),  notice: 'Membership was successfully created'}
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.fetch(:membership, {}).permit(:user_id, :space_id, :membership_type_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>


<section id="pricing-table">
  <div class="container">
    <div class="pricing">
      <% @membership_types.each do |membership_type| %>
          <%= form_for(@membership) do |f| %>
              <%= f.hidden_field :membership_type_id, :value => membership_type.id %>
              <%= f.hidden_field :user_id, :value => @user.id %>
              <%= f.hidden_field :space_id, :value => 1 %>
              <div class="span3 tiny ">
                <div class="pricing-table-header-tiny">
                  <h2>€ <%=membership_type.plan.price%>/mo</h2>
                  <h3><%=membership_type.name%></h3>
                </div>
                <div class="pricing-table-features">
                  <p><strong>€<%=Product.find(membership_type.product_id).price%>/h</strong></p>
                  <p><strong>Any</strong> space</p>
                  <p><strong>9am-6pm</strong> weekdays</p>
                </div>
                <div class="pricing-table-signup-tiny">
                  <%= f.submit "Sign Up", class: "membership_btn"%>
                </div>
              </div>
          <%end%>
      <%end%>
    </div>
  </div>
  </div>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing Memberships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Test</title>
</head>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<div>
  <div class="banner-white-content">
    <img alt="Brand" src="http://www.enklave.de/wp-content/uploads/2016/04/ENKLAVE-Coworking-Space-Berlin-Neuko%CC%88lln-Logo-black.png">
  </div>
</div>

<div class="main-content">

<%= render 'form' %>

<%= link_to 'Back', sign_up_path %>

app/views/memberships/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Test</title>
</head>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<div>
  <div class="banner-white-content">
    <img alt="Brand" src="http://www.enklave.de/wp-content/uploads/2016/04/ENKLAVE-Coworking-Space-Berlin-Neuko%CC%88lln-Logo-black.png">
  </div>
</div>


<div class="main-content">

  <!-- REGISTRATION FORM -->
  <div class="text-center">
    <div class="logo">Sign up complete!</div>
    <!-- Main Form -->
          <p>Thank you for signing up!</p></br>
          <%= link_to 'Edit', edit_membership_path(@membership) %> |
          <%= link_to 'Back', memberships_path %>
      <div class="etc-login-form">
      </div>
    </div>
    </div>
  </div>
</div>
</div>
<!-- end:Main Form -->
</html>