config/routes.rb
Rails.application.routes.draw do
  resources :plans

  namespace :auth do
    resources :sessions
  end

  resources :membership_types
  resources :memberships
  resources :work_sessions
  resources :companies
  resources :purchases
  resources :products
  resources :users do
    member do
      get  :actions
      get :confirmation
      patch :update_confirmation
      get :manage_memberships
      get :manage
      get :set_pin
      patch :update_pin
      get :thank_you

    end
    resources :purchases
    resources :work_sessions do
      member do
        post :checkout
      end
      collection do
        post :checkin
      end
    end
  end
  resources :spaces do
    resources :space_products
  end

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  post '/products/products', to: 'products#tablet'
  post '/tablet/products', to: 'products#tablet'
  post 'tablet/chargebee_products', to: 'products#tablet_chargebee'
  post '/push_cobot_purchase/purchases', to: 'purchases#push_cobot_purchase'
  post '/push_chargebee_purchases', to: 'purchases#push_chargebee_purchase'
  get '/tablet', to: 'users#tablet'
  get '/sign_up', to: 'users#sign_up'

  root 'users#index'

end 

app/models/user.rb
class User < ActiveRecord::Base
  has_many :purchases
  has_many :space_products, through: :purchases
  has_many :work_sessions

  enum auto_collection: [:on, :off]
  enum taxability: [:taxable, :exempt]
  enum entity_code: [:a, :b, :c, :d, :e, :f, :g, :h, :i, :j, :k, :l, :m, :n, :o, :p, :q, :r, :med1, :med2]

  def active_session
    work_sessions.find_by(end_time: nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :logged_in_using_omniauth?
  before_action :set_user, only: [:show, :edit, :update, :destroy, :actions, :confirmation, :update_confirmation]


  # GET /users
  # GET /users.json
  def index
    @users = User.all # User.all
  end

  def tablet
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new

    @user = User.new
  end

  def set_pin

    @user= User.find(params[:id])
  end
  # GET /users/1/edit
  def edit
    @work_session = @user.active_session || WorkSession.new
  end

  def manage_memberships
    @membership_types = MembershipType.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        #UsersApiService.new(@user.attributes).create
        #Auth0Service.new(@user.attributes).create_user
        format.html { redirect_to new_membership_path(:user_id => @user.id) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def sign_up
    @user = User.new
  end
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update_pin
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to thank_you_user_path, notice: 'User pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        UsersApiService.new(@user.attributes).update
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    #UsersApiService.new(@user.attributes).delete
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def actions
    # this should be made specific to the current space
    @products = Space.first.space_products
  end


  def confirmation

    if params[:step].present?
      @step = params[:step].to_i
    else
      @step = 1
    end
  end

  def update_confirmation
      @step = params[:step]
      if @user.update(user_params)
        #UsersApiService.new(@user.attributes).update
        @step = @step.to_i + 1
        #UsersApiService.new(@user.attributes).update
        if @step <=8
          redirect_to confirmation_user_path(@user,  step: @step)
        else
          redirect_to users_path()
        end
      else
        render :confirmation
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :billing_first_name, :billing_last_name, :billing_address_line_1,:billing_address_city, :billing_address_state, :billing_address_zip, :billing_address_country, :current_address_line_1, :current_address_city, :current_address_state, :current_address_zip, :current_address_country, :email, :cell_phone, :auto_collection, :allow_direct_debit, :taxability, :object, :card_status, :promotional_credits, :refundable_credits, :excess_payments, :tablet_pin )
    end
end


def cobot_memberships
  cobot_client.get('etest', '/memberships', attributes: 'name,id')
end
def cobot_client
  CobotClient::ApiClient.new 'd1afe640346642dcb95b40dad20a0d0e118a3a390e523074b1d65df3f17f1b4d'
end

def chargebee_client

end
def chargebee_members
  require 'chargebee'
  ChargeBee.configure(:site => "steventest-test",
                      :api_key => "test_apcdcdFLAJuN2OrjRYvcdQFpbakBg6dszQk")
  list1 = ChargeBee::Customer.list()
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_DOB_details.html.erb
<div class='container'>
  <div class='header'>
    <h1> <%=@user.first_name%>, what's your date of birth? </h1>
    <div class="text-center">
      <div>
        <%= f.label :date_of_birth, 'Date of birth'  %>
      </div>
      <div>
        <%= f.text_field :date_of_birth %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/_phone_details.html.erb
<div class='container'>
  <div class='header'>
    <h1> <%=@user.first_name%>, please enter your cell phone number </h1>
    <div class="text-center">
      <div>
        <%= f.label :cell_phone, 'Cell phone number'  %>
      </div>
      <div>
        <%= f.text_field :cell_phone %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/_pin_details.html.erb
<div class='container'>
  <div class='header'>
    <h1> <%=@user.first_name%>, please enter a four digit pin </h1>
    <div class="text-center">
      <div>
        <%= f.label :tablet_pin, 'Pin'  %>
      </div>
      <div>
        <%= f.text_field :tablet_pin %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/actions.html.erb
<div class='container'>
  <div class='header header-actions'>
    <h2> Hi <%=  @user.first_name %>  what would you like to do or buy? </h2>
  </div>
  <div class='container-actions'>
    <% if @user.active_session.present? %>
        <%= link_to 'Check Out', checkout_user_work_session_path(@user, @user.active_session), class: 'btn btn-default btn-lg', method: :post  %>
    <% else %>
        <%= link_to 'Check In', new_user_work_session_path(@user), class: 'btn btn-default btn-lg' %>
    <% end %>
    <% @products.each do |p|  %>
        <% next unless Product.find(p.product_id).product_type == 'consumable'%>
        <%= link_to p.product.name,  new_user_purchase_path(@user, space_product_id: p.id),   class: 'btn btn-default btn-lg' %>
    <% end %>
  </div>
</div>

app/views/users/confirmation.html.erb
<div class='container'>
  <div class='header'>
    <%= form_for(@user, url: update_confirmation_user_path(@user)) do |f| %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%= hidden_field_tag :step, @step %>
        <% case @step%>
        <%when 1%>
            <%= render partial: 'name_details', locals: {f: f}%>
        <%when 2%>
            <%= render partial: 'address_details', locals: {f: f}%>
        <%when 3%>
            <%= render partial: 'phone_details', locals: {f: f}%>
        <%when 4%>
            <%= render partial: 'dob_details', locals: {f: f}%>
        <%when 5%>
            <%= render partial: 'email_details', locals: {f: f}%>
        <%when 6%>
            <%= render partial: 'vat_details', locals: {f: f}%>
        <%when 7%>
            <%= render partial: 'pin_details', locals: {f: f}%>
        <%when 8%>
            <%= render partial: 'confirm_details', locals: {f: f}%>
        <%else%>
            <%= render partial: 'name_details', locals:{f: f}%>
        <%end%>
        <div class="text-center">
            <div class="container">
              <% case @step%>
              <%when 8%>
                  <div class="row top-buffer">
                    <%= f.submit 'Confirm'%>
                  </div>
              <%else%>
                  <div class="row top-buffer">
                    <%= f.submit 'Next'%>
                  </div>
              <%end%>
              <div class="row top-buffer">
                <%= link_to 'Back', users_path %>
              </div>
        </div>
    <%end%>

    </div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
<h1>Editing account details for <%=@user.first_name %>. </h1>



        </div>

    <% end %>



    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path%>

</div>

app/views/users/index.html.erb
<h1 class="text-center">Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="text-center">
<%= link_to 'New User', new_user_path %>
</div>

app/views/users/manage.html.erb
<div class="wrapper">

  <div class="table">

    <div class="row header">
      <div class="cell">
        Name
      </div>
      <div class="cell">
        Age
      </div>
      <div class="cell">
        Occupation
      </div>
      <div class="cell">
        Location
      </div>
    </div>

    <div class="row">
      <div class="cell">
        Luke Peters
      </div>
      <div class="cell">
        25
      </div>
      <div class="cell">
        Freelance Web Developer
      </div>
      <div class="cell">
        Brookline, MA
      </div>
    </div>

    <div class="row">
      <div class="cell">
        Joseph Smith
      </div>
      <div class="cell">
        27
      </div>
      <div class="cell">
        Project Manager
      </div>
      <div class="cell">
        Somerville, MA
      </div>
    </div>

    <div class="row">
      <div class="cell">
        Maxwell Johnson
      </div>
      <div class="cell">
        26
      </div>
      <div class="cell">
        UX Architect & Designer
      </div>
      <div class="cell">
        Arlington, MA
      </div>
    </div>

    <div class="row">
      <div class="cell">
        Harry Harrison
      </div>
      <div class="cell">
        25
      </div>
      <div class="cell">
        Front-End Developer
      </div>
      <div class="cell">
        Boston, MA
      </div>
    </div>

  </div>

  <div class="table">

    <div class="row header green">
      <div class="cell">
        Product
      </div>
      <div class="cell">
        Unit Price
      </div>
      <div class="cell">
        Quantity
      </div>
      <div class="cell">
        Date Sold
      </div>
      <div class="cell">
        Status
      </div>
    </div>

    <div class="row">
      <div class="cell">
        Solid oak work table
      </div>
      <div class="cell">
        $800
      </div>
      <div class="cell">
        10
      </div>
      <div class="cell">
        03/15/2014
      </div>
      <div class="cell">
        Waiting for Pickup
      </div>
    </div>

    <div class="row">
      <div class="cell">
        Leather iPhone wallet
      </div>
      <div class="cell">
        $45
      </div>
      <div class="cell">
        120
      </div>
      <div class="cell">
        02/28/2014
      </div>
      <div class="cell">
        In Transit
      </div>
    </div>

    <div class="row">
      <div class="cell">
        27" Apple Thunderbolt displays
      </div>
      <div class="cell">
        $1000
      </div>
      <div class="cell">
        25
      </div>
      <div class="cell">
        02/10/2014
      </div>
      <div class="cell">
        Delivered
      </div>
    </div>

    <div class="row">
      <div class="cell">
        Bose studio headphones
      </div>
      <div class="cell">
        $60
      </div>
      <div class="cell">
        90
      </div>
      <div class="cell">
        01/14/2014
      </div>
      <div class="cell">
        Delivered
      </div>
    </div>

  </div>

  <div class="table">

    <div class="row header blue">
      <div class="cell">
        Username
      </div>
      <div class="cell">
        Email
      </div>
      <div class="cell">
        Password
      </div>
      <div class="cell">
        Active
      </div>
    </div>

    <div class="row">
      <div class="cell">
        ninjalug
      </div>
      <div class="cell">
        misterninja@hotmail.com
      </div>
      <div class="cell">
        ************
      </div>
      <div class="cell">
        Yes
      </div>
    </div>

    <div class="row">
      <div class="cell">
        jsmith41
      </div>
      <div class="cell">
        joseph.smith@gmail.com
      </div>
      <div class="cell">
        ************
      </div>
      <div class="cell">
        No
      </div>
    </div>

    <div class="row">
      <div class="cell">
        1337hax0r15
      </div>
      <div class="cell">
        hackerdude1000@aol.com
      </div>
      <div class="cell">
        ************
      </div>
      <div class="cell">
        Yes
      </div>
    </div>

    <div class="row">
      <div class="cell">
        hairyharry19
      </div>
      <div class="cell">
        harryharry@gmail.com
      </div>
      <div class="cell">
        ************
      </div>
      <div class="cell">
        Yes
      </div>
    </div>

  </div>

</div>

app/views/users/manage_memberships.html.erb
<section id="pricing-table">
  <div class="container">
      <div class="pricing">
        <% @membership_types.each do |membership_type| %>
            <div class="span3 tiny ">
              <div class="pricing-table-header-tiny">
                <h2>€ <%=Plan.find(membership_type.plan_id).price%>/mo</h2>
                <h3><%=membership_type.name%></h3>
              </div>
              <div class="pricing-table-features">
                <p><strong>€<%=Product.find(membership_type.product_id).price%>/h</strong></p>
                <p><strong>Any</strong> space</p>
                <p><strong>9am-6pm</strong> weekdays</p>
              </div>
              <div class="pricing-table-signup-tiny">
                <p><a href="#">Sign Up</a></p>
              </div>
            </div>
        <%end%>
      </div>
  </div>
</div>

app/views/users/set_pin.html.erb
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Test</title>
</head>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<div>
  <div class="banner-white-content">
    <img alt="Brand" src="http://www.enklave.de/wp-content/uploads/2016/04/ENKLAVE-Coworking-Space-Berlin-Neuko%CC%88lln-Logo-black.png">
  </div>
</div>

<div class="main-content">

  <!-- REGISTRATION FORM -->
  <div class="text-center">
    <div class="logo">Enter a 4 digit PIN</div>
    <!-- Main Form -->
    <div class="login-form-1">
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">
          <%= form_for @user, :url => { :action => "update_pin"} do |f| %>
            <%= render partial: 'shared/pinpad' %>
          <%end%>
        </div>
      </div>
      <div class="etc-login-form">
        <p>This will be used for checking in, out, and purchasing products. </p>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p>
  <strong>User:</strong>
  <%=@user.first_name%>
  <%=@user.last_name%>

</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/sign_up.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<div>
  <div class="banner-white-content">
    <img alt="Brand" src="http://www.enklave.de/wp-content/uploads/2016/04/ENKLAVE-Coworking-Space-Berlin-Neuko%CC%88lln-Logo-black.png">
  </div>
</div>

<div class="main-content">
  <div class="text-center">
    <div class="logo">Sign Up</div>
    <div class="login-form-1">
        <div class="login-form-main-message"></div>
        <div class="main-login-form">
          <div class="login-group">
            <%= form_for @user , :url => {:action => "create"} do |f| %>
                <div class="form-group">
                  <%= f.label :first_name, class:"sr-only"%>
                  <%= f.text_field :first_name, class: "form-control", placeholder:"first name"  %><br />
                </div>
                <div class="form-group">
                  <%= f.label :last_name, class:"sr-only"%>
                  <%= f.text_field :last_name, class: "form-control", placeholder:"last name"  %><br />
                </div>
                <div class="form-group">
                  <%= f.label :email, class:"sr-only"%>
                  <%= f.text_field :email, class: "form-control", placeholder:"email"  %><br />
                </div>
                <div class="form-group">
                  <%= f.label :password, class:"sr-only"%>
                  <%= f.password_field :password, class: "form-control", placeholder:"password"  %><br />
                </div>
                <%= button_tag(type: 'submit', class: "login-button") do %>
                    <i class="fa fa-chevron-right"></i>
                <% end %>
            <% end %>
          </div>
        </div>
        <div class="etc-login-form">
          <p>already have an account? <a href="#">login here</a></p>
        </div>
    </div>
  </div>
</div>
</div>

app/views/users/tablet.html.erb
<div class='container'>
  <div class='header'>
      <h1> Welcome to Enklave! </h1>
      <h2> Who's there? </h2>
      <div class='container-users'>
          <% @users.each do |u| %>
            <%= link_to u.first_name, actions_user_path(u), class: 'btn btn-default btn-lg' %>
          <% end %>
      </div>
  </div>
</div>

app/views/users/thank_you.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Test</title>
</head>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<div>
  <div class="banner-white-content">
    <img alt="Brand" src="http://www.enklave.de/wp-content/uploads/2016/04/ENKLAVE-Coworking-Space-Berlin-Neuko%CC%88lln-Logo-black.png">
  </div>
</div>


<div class="main-content">

  <!-- REGISTRATION FORM -->
  <div class="text-center">
    <div class="logo">Sign up complete!</div>
    <!-- Main Form -->
    <p>Thank you for signing up!</p></br>

    <div class="etc-login-form">
    </div>
  </div>
</div>
</div>
</div>
</div>
<!-- end:Main Form -->
</html>