config/routes.rb
Rails.application.routes.draw do
  resources :plans

  namespace :auth do
    resources :sessions
  end

  resources :membership_types
  resources :memberships
  resources :work_sessions
  resources :companies
  resources :purchases
  resources :products
  resources :users do
    member do
      get  :actions
      get :confirmation
      patch :update_confirmation
      get :manage_memberships
      get :manage
      get :set_pin
      patch :update_pin
      get :thank_you

    end
    resources :purchases
    resources :work_sessions do
      member do
        post :checkout
      end
      collection do
        post :checkin
      end
    end
  end
  resources :spaces do
    resources :space_products
  end

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  post '/products/products', to: 'products#tablet'
  post '/tablet/products', to: 'products#tablet'
  post 'tablet/chargebee_products', to: 'products#tablet_chargebee'
  post '/push_cobot_purchase/purchases', to: 'purchases#push_cobot_purchase'
  post '/push_chargebee_purchases', to: 'purchases#push_chargebee_purchase'
  get '/tablet', to: 'users#tablet'
  get '/sign_up', to: 'users#sign_up'

  root 'users#index'

end 

app/models/work_session.rb
class WorkSession < ActiveRecord::Base
  after_create :set_start_time

  belongs_to :user
  belongs_to :space

  def set_start_time
    update_attribute(:start_time, Time.now)
  end

  def set_end_time
    update_attribute(:end_time, Time.now)
  end
end

app/controllers/work_sessions_controller.rb
class WorkSessionsController < ApplicationController
  skip_before_filter :logged_in_using_omniauth?
  before_action :set_work_session, only: [:show, :edit, :update, :destroy, :checkout]

  def index
    @work_sessions = WorkSession.all
  end

  def show
  end

  def new
    @user = User.find(params[:user_id])
  end

  def edit
  end

  def create
    @work_session = WorkSession.new(work_session_params)

    respond_to do |format|
      if @work_session.save
        format.html { redirect_to edit_user_path(@work_session.user), notice: 'Session was successfully created.' }
        format.json { render :show, status: :created, location: @work_session }
      else
        format.html { render :new }
        format.json { render json: @work_session.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @work_session.update(work_session_params)
        format.html { redirect_to @work_session, notice: 'Work Session was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_session }
      else
        format.html { render :edit }
        format.json { render json: @work_session.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work_session.destroy
    respond_to do |format|
      format.html { redirect_to work_sessions_url, notice: 'Work Session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def checkout
    @work_session.set_end_time
    respond_to do |format|
      flash[:success] = "You have been checked out successfully."
      format.html { redirect_to '/tablet' }
      format.json { head :no_content }
    end
  end

  def checkin
    @work_session = WorkSession.create(user_id: params[:user_id], space_id: Space.first.id )
    @work_session.set_start_time
    respond_to do |format|
      flash[:success] = "You have been checked in successfully."
      format.html { redirect_to '/tablet' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_session
      @user = User.find(params[:user_id])
      @work_session = WorkSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_session_params
      params.require(:work_session).permit(:start_time, :end_time, :user_id, :space_id)
    end
end

app/views/work_sessions/_form.html.erb
<%= form_for(@session) do |f| %>
  <% if @session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@session.errors.count, "error") %> prohibited this session from being saved:</h2>

      <ul>
      <% @session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_sessions/edit.html.erb
<h1>Editing Session</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_session %> |
<%= link_to 'Back', sessions_path %>

app/views/work_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing sessions for <%= @user.first_name%>  <%= @user.last_name%> </h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_sessions.each do |work_session| %>
      <tr>
        <td><%= work_session.start_time %></td>
        <td><%= work_session.end_time %></td>
        <td><%= work_session.user_id %></td>
        <td><%= link_to 'Show', work_session %></td>
        <td><%= link_to 'Edit', edit_work_session_path(work_session) %></td>
        <td><%= link_to 'Destroy', work_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Session', new_session_path %>

app/views/work_sessions/new.html.erb
<div class='container'>
  <div class='header'>
    <h2> So, Check In for <%= @user.first_name %> ? </h2>
  </div>
   <div class='container-actions'>
      <%= link_to 'Yes', checkin_user_work_sessions_path(@user) , class: 'btn btn-default btn-lg', method: :post %>
      <%= link_to 'No', '/tablet', class: 'btn btn-default btn-lg' %>
  </div>
</div>

app/views/work_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @work_session.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @work_session.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @work_session.user_id %>
</p>

<%= link_to 'Edit', edit_work_session_path(@work_session) %> |
<%= link_to 'Back', work_sessions_path %>