config/routes.rb
Rails.application.routes.draw do
  resources :plans

  namespace :auth do
    resources :sessions
  end

  resources :membership_types
  resources :memberships
  resources :work_sessions
  resources :companies
  resources :purchases
  resources :products
  resources :users do
    member do
      get  :actions
      get :confirmation
      patch :update_confirmation
      get :manage_memberships
      get :manage
      get :set_pin
      patch :update_pin
      get :thank_you

    end
    resources :purchases
    resources :work_sessions do
      member do
        post :checkout
      end
      collection do
        post :checkin
      end
    end
  end
  resources :spaces do
    resources :space_products
  end

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  post '/products/products', to: 'products#tablet'
  post '/tablet/products', to: 'products#tablet'
  post 'tablet/chargebee_products', to: 'products#tablet_chargebee'
  post '/push_cobot_purchase/purchases', to: 'purchases#push_cobot_purchase'
  post '/push_chargebee_purchases', to: 'purchases#push_chargebee_purchase'
  get '/tablet', to: 'users#tablet'
  get '/sign_up', to: 'users#sign_up'

  root 'users#index'

end 

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :space_products
  has_many :spaces, through: :space_products
  has_many :membership_types, dependent: :nullify

  monetize :price_cents, as: :price, :disable_validation => true

  enum product_type: [:consumable, :membership]
  enum type: [:on_off, :quantity] #refer to chargebee documentation
  enum charge_type: [:recurring, :non_recurring]
  enum period_unit: [:week, :month, :year, :not_applicable]
  enum status: [:active, :archived, :deleted]
  has_one :company

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :logged_in_using_omniauth?
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_products, only: [:index]

  def tablet
    @tablet_products = cobot_products
    @member = params

  end

  def tablet_chargebee
    @chargebee_tablet_products = chargebee_products
    @member = params
  end

  # GET /products
  # GET /products.json
  def index
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new

  end

  # GET /products/1/edit
  def edit
    @product_type = Product.find(params[:id]).product_type
    #if @product_type.nil? then @product_type = "not set" end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        ProductsApiService.new(@product.attributes).create
        #ProductsApiService.new(@product.attributes).create
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        #ProductsApiService.new(@product.attributes).update
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    #ProductsApiService.new(@product.attributes).delete
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_products
      if params[:space_id].present?
        @space = Space.find(params[:space_id])
        @products = @space.products
      else
        @products = Product.all
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :product_type, :price)
    end
end

def cobot_products
  cobot_client.get('etest', '/resources', attributes: 'name,id')
end

def cobot_client
  CobotClient::ApiClient.new '92dc92196ce9fedbf18f5d759c98abee3ea01e0fa320d90f5146578a593014a9'
end

def chargebee_products
  require 'chargebee'
  ChargeBee.configure(:site => "steventest-test",
                      :api_key => "test_apcdcdFLAJuN2OrjRYvcdQFpbakBg6dszQk")
  list = ChargeBee::Addon.list
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="text-center">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
        <div class="field">
          <%= f.label 'Product Type' %><br>
          <% if (@product.product_type.nil?) %>
              <%= f.select(:product_type, options_for_select(Product.product_types.keys.map {|product_type| [product_type.capitalize, product_type]}.insert(0, ""))) %>
          <% else%>
              <%= f.select(:product_type, options_for_select(Product.product_types.keys.map {|product_type| [product_type.capitalize, product_type]}, selected: @product.product_type)) %>
          <% end%>
        </div>
      <div>
          <p>
            <%= f.label :price %><br>
            <%= f.text_field :price, data: { role: 'money', a_sep: '.', a_dec: ',' } %>
          </p>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1 class="text-center">Editing Product</h1>

<%= render 'form' %>


<%= link_to 'Show', @product %> |



<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="text-center">Listing Products</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Product ID</th>
      <th>Product name</th>
      <th>Product price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="text-center">
    <%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1 class="text-center">New Product</h1>
<%= render 'form' %>

<div class="text-center">
    <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @product.id %>
  <%= @product.name %>
</p>
<p>
  <strong>Product Type:</strong>
  <%= @product.product_type %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/tablet.erb
<div class="text-center">
  <h1>Hi <%= @member[:name] %>, what would you like to do?</h1>
  <% @tablet_products.each_slice(3) do |products| %>
      <p class="row">
        <% products.each do |product| %>

          <div class="col-md-4">
            <%= button_to product[:name], push_cobot_purchase_purchases_path('etest'), params: product.merge(:membership_id => @member[:id]).as_json, class: 'btn btn-primary btn-lg'%>

          </div>
      <%end%>
      </p>
  <% end %>
</div>

app/views/products/tablet_ChargeBee.erb
<div class="text-center">
  <h1>Hi <%= @member[:'first_name'] %>, what would you like to do?</h1>
    <% @chargebee_tablet_products.each_slice(11) do |entrys| %>
      <p class="row">
        <% entrys.each do |entry| %>
          <div class="col-md-3">
            <%= button_to entry.addon.name, push_chargebee_purchases_path, params: entry.addon.as_json.merge(@member[:'id']),class: 'btn btn-primary btn-lg'%>
          </div>
        <%end%>
      </p>
    <% end %>
</div>